name: 'Publish to Container Registry'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of application'
  push:
    branches:
      - main
    path:
      - _versions

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_APP_EMAIL}}